/// Generated by AssetsRefGenerator on 2023/08/23
class Res {
  static const String abdallah = "assets/images/abd.jpeg";
  static const String home_1 = "assets/images/home_1.png";
  static const String home_2 = "assets/images/home_2.png";
  static const String home_3 = "assets/images/home_3.png";
  static const String img = "assets/images/img.png";
  static const String img_1 = "assets/images/img_1.png";
  static const String img_2 = "assets/images/img_2.png";
  static const String img_3 = "assets/images/img_3.png";
  static const String img_4 = "assets/images/img_4.png";
  static const String circleAvatar = "assets/images/img_7.png";
  static const String InterTight_Italic_VariableFont_wght = "assets/fonts/InterTight-Italic-VariableFont_wght.ttf";
  static const String InterTight_VariableFont_wght = "assets/fonts/InterTight-VariableFont_wght.ttf";
  static const String PilatExtended_Book = "assets/fonts/PilatExtended-Book.ttf";
}
